#+TITLE: 算法 4th
#+STARTUP: overview
* 提出问题
- 全书讲了什么
- 全书是如何组织的
- 这本书和我有什么关系
* 阅读的目的
学习基本的算法为之后找到更好的工作打下基础,大概在3个月之内过一遍这本书,习题基本上每个算法相关的题都做一遍吧.
* 书籍的简单摘要
讲解了多种重要而实用的算法和数据结构, 在java语言上实现了这些算法,并且详尽的分析了这些算法的性能特点和用途
* 结构
** 基础
介绍JAVA的基础,基本的数据结构(背包,队列,栈),算法性能分析的方法(先对性能提出假设,建立数学模型,用多种实验验证它们)
*** 1.1
总结了相关的语法,语言特性和书中将会用到的库
*** 1.2
数据的抽象,如何构造类来对对象进行抽象,作者基于工程上的经验给出了一些建议
*** 1.3
介绍4种基本的数据结构,背包,队列,栈,讲解了泛型,使用链表来实现这三种数据结构
*** 1.4 算法分析
- 时间分析
  1. 确定输入模型
  2. 识别内循环
  3. 根据内循环中的操作确定成本模型
  4. 对于给定的输入,判断这些操作的执行频率
- 空间分析
  Java的内存分配,对程序员是隐藏的.但是可以根据使用的变量类型和变量数量来进行粗略的分析.
  由于垃圾回收的机制,以及java是运行在jvm上的,这就导致难以像分析C++或者C这样更加偏向底层的程序一样细致得分析java的程序

过早优化是万恶之源.在数据量变得无比巨大的时候必须要考虑优化算法.
*** 1.5 案例研究
通过研究 union-find算法来学习之前提到的算法分析的内容
** 排序
*** 初级排序算法
*** 归并排序算法
*** 快速排序算法
*** 优先队列
** 查找
*** 符号表
*** 二叉查找树
*** 平衡查找树
*** 散列表
** 图
*** 无向图
*** 有向图
*** 最小生成树
*** 最短路径
** 字符串
*** 字符串排序
*** 单词查找树
*** 子字符串查找
*** 正则表达
*** 数据压缩
** 背景
* 算法整理
* 习题集
#+BEGIN_SRC java :session algs4
import edu.princeton.cs.algs4.*;
#+END_SRC
** Chapter one
* 吐槽
- 讲解的内容太细碎,第一章看得有点难受,在一堆已经知道的东西里面寻找自己未知的东西
- 讲得比较细碎，还是直接看算法导论吧。
