#+TITLE: Introduction to Algorithms 3th
#+STARTUP: overview
* 提出问题
- 全书讲了什么
- 全书是如何组织的
- 这本书和我有什么关系
* 阅读的目的
学习基本的算法为之后找到更好的工作打下基础,大概在3个月之内过一遍这本书,习题基本上每章的题都做一遍吧.
* 书籍的简单摘要
This book provides a comprehensive introduction to the modern study of computer algorithms
* 结构
** Fundations
*** Introduction
The fundation of algorithms
*** The Role of Algorithms in Computing
overview of algorithms and their place in modern computing systems
An =Algorithms= is any well-defined computational procedure that takes some value, or set of values, as input and produces some value, or set of values, as output. In other words, An algorithms is thus a sequence of computational steps that transform the input into output.
An =Algorithms= is correct if, for every input instance, it halts with the correct output.
*** Getting Started
An insertion sort example
#+BEGIN_SRC cpp
  #include <iostream>
  using namespace std;

  int[] sort(int l[], int length) {
    for (int i = 0; i < length; i++) {
    }
    int i[] = [ 1, 2, 3 ];
    return i;
  }

  int main(int argc, char *argv[]) { return 0; }
#+END_SRC
*** Growth of Functions
precisely defines asymptotic notation
*** Divide-and-Conquer
Delve into divide-and-conquer method.
*** Probabilistic Analysis and Randomized Algorithms
Introduce probailistic analysis and randomized algorithms
** Sorting and Order Statistics
** Data Structures
** Advanced Design and Analysis Techniques
** Advanced Data Structures
** Graph Algorithms
** Selected Topics
** Appendix
* 习题集
* 吐槽
