# -*- mode: org; coding: utf-8 -*-
#+TITLE: The Scientific Revolution and the Origins of Modern Science
#+STARTUP: overview
* 提出问题
- 全书讲了什么
- 全书是如何组织的
- 讲得是否有道理(实用类书籍不做)
- 这本书和我有什么关系
* 书籍的简单摘要
辨析了科学革命这一概念，叙述了科学革命出现的时代背景以及科学革命出现的原因
* 结构
** 科学革命与科学史写作
科学革命,指欧洲史的一个时期，历史学家认为正是这个时期，真正奠定了现代科学在概念方面、方法论方面、机制方面的根基。

17世纪与15世纪欧洲人对自然知识的态度的差别:
1. "全然思辨性的、基本上受之亚里士多德思想的自然哲学"转变为"关于自然的知识有实际的用途"
2. "仰赖古人的权威，以之为知识的神圣之源"转变为"要获取有关自然世界的知识，只能第一手的研究这个世界，或是细致的观察，或是精心设计的调查实验"
3. 逐渐认为数学是揭示自然现象运行所必需的手段
4. 开始要以具体确切的法则来丰富"自然法"
5. "自然物品与人造的物品的对立"转变为"以与人为进程类比的角度来理解自然",具体的，不再相信卫星之下的一切由土、水、气、火四元素组成,而是认为天上的与地上的并非截然有别，一切事物都是由看不见的小微粒组成，都从属相同的、普遍的自然法则。
6. 不再信奉有限的、以地球为中心的宇宙，而是无限的宇宙，太阳不过是群星之一。

辉格史学:关注以前的时候，只是盯着后来被证明是重要的那部分。依据现在来判断过去。

科学革命简单概括就是:中世纪的自然哲学，原本不想沾染数学以及其他更实用或更依赖实验的技艺与科学，最终却还是与这些方法合在一起形成了对自然的分析，导致了与我们现在的科学概念更相近的东西。

** 文艺复兴与科学革命
文艺复兴产生的原因:
1. 罗马天主教会和所谓的神圣罗马帝国愈来愈不能够给有组织的精神生活和物质生活提供必要的稳定性。
2. 自治市、地区力量和民族力量的兴起
3. 地方封建司法权的出现
4. 以私人资本为基础的商业的发展,出现了银行体系
5. 发现并且开发了新世界
6. 文化相对主义的概念

大量古代文献被重新发现，动摇了中世纪以来亚里士多德在哲学方面的统治地位,作为替代的哲学体系繁荣发展，由此出现的一个深远的变化是，越来越多的强调个人对真理的寻找应出自个人的经验和努力。于此同时，路德提出“信徒皆祭司”，敦促个人自己去寻找整理，回到源头也就是圣经中去寻找真理。而在同时代，自然界被人为是“上帝的另一本书”。由此诞生了科学革命的一个代表特征，全新地强调经验和观察是寻找真理的手段。
科学革命的另外一个代表特征是，关于自然的知识肯定有益于人类生活的改善。这点导致了对于数学科学和法术技能的重视。
科学革命的第三个特征是，越来越多的运用数学来理解自然世界的运作。(柏拉图认为数学是获得特定知识极好的手段)
** 科学的方法
科学的方法有两个主要的基本内容:
1. 运用数学和计量以精确测度世界及其各个部分是怎样运作的
2. 运用观察、经验以及人为控制的实验来理解自然
*** 世界图像的数学化
工具主义者(instrumentalists): 认为数学所得出的理论只是假设而已，关键还是要利用数学得出的计算与预测。(亚里士多德的主张，数学分析给不出因果解释，所以也就无益于自然哲学)
为实论者(realists): 认为数学分析揭示了事情怎么就必定是那样子的,如果计算是正确的，那么这说明说设想的理论是接近与真实的。
从工具主义的观点转变为为实论的观点是科学革命的一个重要的内容，即世界图像的数学化。

哥白尼通过计算给出了日心说，他认为，不管这一点怎么样抵触了自然哲学，也必定是真实的，因为这是数学所要求的结果。这一点是革命性的。
在1600年之前，只有10位思想家认可了哥白尼的理论是自然真理，其余的都把哥白尼的理论看作是一种为了方便计算而给出的模型。

数学地位的提高不只出现在天文领域，还出现在了更加实用的领域诸如(航海，测量和绘图),这些都促成了早期数学家们地位的提高，以及恩主阶层里的成员对于数学有越来越浓厚的兴趣。

自然哲学的数学原理的出版标志着自然哲学数学化的完成。牛顿在本书中，虽然采用了胡克的假设，但是当时的人们都普遍认为相对与牛顿依据精确的数学说进行的工作相比胡克的假设委实渺小.
*** 经验与实验
数学家们想要确立他们理解世界的方法的有效性,就得确立新的核定标准,新的权威原则.
科学革命的一个代表特征就是,用途明确的实验(experiments)所论证的知识概念取代了自明的经验(experience).
数学传统是17世纪科学的实验方法的一个主要来源
文艺复兴时期的学者们越来越多地注意到了杰出的技工们的实用知识,这也是实验方法得以形成的一个重要因素.
炼金术的那种实验主义扩展到了自然哲学家,内科医生和其他由于数学,自然史,解剖学和医学领域里的发展而信服经验思想的人当中.
** 法术与现代科学的起源
** 机械论哲学
** 宗教与科学
** 科学与广义文化
* 阅读的目的
了解科学革命这一概念
* 吐槽
