# -*- mode: org; coding: utf-8 -*-
#+TITLE: How To Read A Book (如何阅读一本书)
#+STARTUP: overview
* 提出问题
- 全书讲了什么 :: 见全文摘要一节
- 全书是如何组织的 :: 见结构一节
- 这本书和我有什么关系 :: 见阅读目的一节
* 全文摘要
本书论述了阅读的四个层次,并且就第三层次--分析阅读做了详细的说明,给出了具体的操作步骤
* 阅读的目的
阅读本书的目的在于想要学习如何能够更好的从书中学习,具体而言,如何更好的学习cs以及数学类的书籍, 至于人文社科之类的不再我的考虑范畴,因此对于本书只是着重阅读前两篇关于一般的通用法则的内容(第十章之后的内容不关注)
* 结构
** 第一篇
*** 第一章 :: 阅读的活力与艺术
主要论述阅读的目的,以及不同阅读目的之间具体操作的区别.
阅读就是学习,是一种老师缺位的自主学习
*** 第二章 :: 阅读的层次
简单的论述阅读的层次,具体的分为
- 基础阅读
  完成基本程度的阅读,即能够理解这本书上的文字
- 检视阅读
  抓住全书的重点,明白全书讲了些什么
- 分析阅读
  即是全盘式的阅读,本书论述的重点,具体在第二篇会有详细的论述
- 主题阅读
  即是阅读同一主题的许多本书,通过对比许多本书最终得出新的理解

越往下,需要耗费的精力越多,能够获得的理解能力也越多.
*** 第三章 :: 基础阅读
简单的论述了一下基础阅读,以及吐槽了一下美国的教育系统
*** 第四章 :: 检视阅读
强调了检视阅读的重要性,阅读没一本书之前最好都做一下检视阅读,理清楚书的结构,有个大体的把握
给出了检视阅读的具体操作步骤
- 先看书名,如果有序就看序
- 研究目录页
- 如果书中有索引也要阅读一下索引
- 阅读一下出版者和作者的介绍
- 开始挑几个和主题息息相关的篇章来看,如果有篇章的摘要需要仔细阅读
- 最后把一本书打开,随意乱看几页.把握全书的主体
   
如果遇到读不懂的章节,先跳过过完全书之后再来看,进度优先,先有一个全局的把握, 同理也可以有选择的略过一些细节
*** 第五章 :: 如何做一个自我要求的读者
一个阅读者在阅读每一本书的时候都需要提出四个基本问题
- 整体来说,这本书在谈论什么
- 作者细部说了什么,都是怎么说的 (也即全书是如何组织的)
- 这本书说得有道理吗?是全部有道理还是部分有道理(实用类书籍不需要回答这个问题)
- 这本书和你有什么关系
  
三种做笔记的方式
- 结构笔记 :: 回答上述前两个问题的笔记 即检视阅读的笔记
- 概念笔记 :: 整理作者的观点以及对观点的论证 即分析阅读的笔记
- 辩证笔记 :: 同时阅读好几本关于同一主题的书,即主题阅读的笔记
** 第二篇
分析阅读的规则 (第一阶段) 找出一本书在谈什么的规则
1. 依照书本的种类与主题作分类
2. 使用单一的句子,或者最多几句话来叙述整本书的内容
3. 将书中重要的篇章列举出来,说明他们如何按照顺序组成一个整体的框架.将全书的纲要拟出之后,各个部分的
4. 找出作者要问的问题 (作者在写书的时候是带着一个问题的,而写的书就是答案,如何根据书籍反推出作者的问题.)
分析阅读的规则 (第二阶段) 诠释一本书内容的规则
5. 诠释作者使用的关键字,与作者达成共识
6. 从最重要的句子中抓出作者的重要主旨
7. 找出作者的论述,重新架构这些论述的前因后果,以明白作者的主张
8. 确定作者已经解决了哪些问题,还有哪些问题没有解决,在没有解决的问题中确定哪些是作者认为自己无法解决的.
*** 第六章 :: 一本书的分类
仔细的论述了如何为一本书分类,意义不大,考虑到有搜索引擎,直接问谷歌就好了.
这章为之后的第三篇提供的实践的准则,即先为书籍分类,然后根据书籍的分类有针对性的阅读
*** 第七章 :: 透视一本书
即对第三章检视阅读的扩充,具体可以分成几步走:
1. 叙述整本书的大意
2. 为一本书拟大纲
   具体的公式如下: 作者将全书分成X个部分,每个部分分别谈论.... 第X个部分又可以被分为... 每个部分主要讲... 
   一般不会这样详细的列举,只在阅读非常好的书籍的时候才会这样做. 
   大纲不必跟书籍的目录一样
3. 找出作者要问的问题
   一般在阅读书籍的过程中自然而然就会得出了.
*** 第八章 :: 与作者找出共通的词义
主要是辨析词义的章节,对于受过高等教育的读者来说借鉴意义比较少. 可以略过,遇到不懂的术语可以谷歌一下
对于很难读懂的书,最重要的书找出书中的关键字,即书中反复提及的字
*** 第九章 :: 判断作者的主旨
找出关键句,根据关键句,找出主旨.
围绕主旨找出论述
为第七章中提及的作者的问题找出解答
主要是论述类的书籍,对于实用性的书籍不需要繁琐的判断作者的主旨是否正确,以及作者是如何对自己的主旨进行判断
